# The standard config server port is 8888.
server:
  port: 8888

# Turn off authentication on secured actuator endpoints.
management:
  security:
    enabled: false

# The configuration repository.
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.ford.com:JPOTTE46/central-config.git
          ignoreLocalSshSettings: true
          privateKey: |
                       -----BEGIN RSA PRIVATE KEY-----
                       MIIJKQIBAAKCAgEAnMq/adADO5lLCRIg6cSKA8p+LCCFvgV7HjolgHkOTjnWQm/d
                       cM0Ou/XQQqAW/O3MN/TzrQoCBmxG+5FF/F1akRtNRF4po3bUOfefmji6c4MRoLxr
                       ekCzqoOhIvund7if92fTF51ab450EFDmau5c8J88Vqf70e8bimswjm9VEmF0jPzH
                       blYqJiJ2tX4/WcnisbQpmoma1Imu3TQRkYJzbBz+1Gbgd83PgEMhN4veIQ1yraO0
                       ycy6ErAeJcpCMU4M7ZbtMi/9C+uoq/XzyIHJ+iHZlfsFtJ/3Ol7CsLnjM4/gWTjg
                       fyxHbXajHJuSkSKZAAEAdRoXkJnF6BTPWTMh1qJ9TVe4l2M+ZsXkJNEO2sMnmHZI
                       zqO2ZfbwT9C4mrW3tDemWlpsAu7yNVJrAWlWBHGOodAISTBRkGrl3gajO0y3W/io
                       PGNlA55Vq3b/APztJQ4OC9p4bYUq0S7KkQzaut9Xob5P0GjbD9viIL7DCiKgMMzl
                       rdetK7Xxa+iExbK8O6pDPLO40/XigcdBl1c9ibh2BG6mhVBvpzWF3KoouyJ9zn8x
                       88SLJ2lVTv8VF+CWsZS8B1UikaM+83Z7uzdsE/+AsRy9Ir7dRzSiTEruco3Y3pRD
                       JhLx7DDePtr3qla4I9WRwyCYaExqtagdut3ByzCKauU0HNK9AcR30+pEBG0CAwEA
                       AQKCAgAyHcxZMhgWcMU/PQAwOJY06AC0ciDNwEq+Oq/KBOfBsVL/IWqSp7jR85yB
                       71HpvsjMCgvpf41uKCX4O1M3e097mlJ0S/TbPxxO+wuU7BUM3xQ/YHqqNQw4sKJM
                       4EuDRQw8tH8QyUci6VHH9VPxUgd7EirjOAaR7+/JqsF2hbeXjHcIqbPFXN1UGyf+
                       k0AEnzdKvd+eeeV3khrGseH7tMrX/9ykX83X/X0Z7lsruhViUz4Yqn8bEclYN9sr
                       ER9fSyduuhNPO2+S49yiOpeVu4an4TH/cqE8PvVzPt7URlaNIKwBWODJRYn/PzCb
                       8E5E/d4R1kAjLhfiLITJzf0I8gMaa/nJiJIPv6piYpCe7Mr9CMge3LR/PPPD7/Ql
                       WeTLLRDiF/3uTpUO7NQ0oC768l6zXM9j6wtoRrVfLAU+LKr4OE4KRT9CDerJokLi
                       oapTnoLgRs05jXYI3wHdDmWUFrXlZ3t7d+p405gdEvG0JfubF7bYbnYMDgPuVFHJ
                       trBfuMRcYnmYa9ZqWLCa1SgweOon3aSPK4HqKukSAietI5On4/kkym3gwp/iknm1
                       VLBuXXUiictVD2VQMbgH5TCb6EWuihLyVBPrNPibfZbADNUZlnEDakETyge3VEsR
                       ptZrcZsD7IHhlpI63KwfwLEiCLJ97uYaIk9BhALisnuujMOEgQKCAQEAyJ8FJKrM
                       sslZVy9tgoZYC6IGTNEc2Axk56TuhlpX9YlXizHfq9y2/g0oen1TEedeRcYR2Jv3
                       3uCQx3yE090ezWxR6dO8YsqzHasQ86lZ/jMN9V8HYodBxwLN/GQnEDRPV0BtnVZK
                       bkzu4YJ0Lar0V1TgkOZK0A1ADF/m2oW1op0ODI1HhrJmpiZOzqU/dn8XKGGF/NZA
                       Ih1VW1HGbj2U3+yX4QVGgKSIeiWs8bU7l2A9kPkb0VMn1xrdavZlctf6B1zO1Nhj
                       yVUctOjq/l5PRcXwEXdLo4niUwNFgE9WqPomijNQPC5vRVqTGmagUceczLAsNvhU
                       nLkejbz8FhphZQKCAQEAyBKE+yMAyBcsEgk3aWU+YZ7MhKRfzRgHXnvbIXnRUc18
                       fFqXkL+4ojQsg85CicLzdgDE0/3Ask6o5yiAuKZ5I6iq5Dv+ZjhbyCB/kmD6O4G+
                       NOtutQ0BckGs3czkJFGbUoEMS+tKEmYJYQr4lWYW1DdRicn51Tn+0klX+pB1xkI2
                       k2vQ1p1Ayj+mtFVL41n7x5sbjbZkBBiT5xaFc68tNLiBgwMJ1+kZZ/jvdBrZbX1u
                       Z/9aciJr6UW/KkMV0XbVx9NeaBR25Q+Eaq1VuArm9zCUuM5SQhkTcpOtzoJdpoa7
                       poN5+Yia1/PHFWdLHTO7sZNzIIE/M3fnDw6En+GqaQKCAQEAwRsfrj2hLu5USnFi
                       bWK22OuqOMKHiwXTEo1U8ol/ZN5AH8Fv1FNs6Hjt34lGLlOQEIUopGDsY+GwOfQH
                       Po72mTCMYA/oowcNBZ+lf4QhFWc7JlXEG/ipPc/bSfd1CknvnMJtQCbRGf5/aR1S
                       iqqk6nLOfWrN1BkM71xYLzrIrK+T2E0c7fBGkeMJtCqnPX3zYnEMsWPg83Vctbuu
                       zmoEJM3tGzEivayhmUEuiLGznG+Mk0DUn9X04T4ApnZpC/QLvI5+n61xz1dXfGM9
                       3n4Uu8pc29MCQXX1HYZmnazAc4HlGt1te6AOhqk6Mw1Zf54ttXBV/stlVj1xxWiF
                       FRlraQKCAQEAoKeGUubzjLhWshDmhuI+akMKdQRMzTKbUDpiZoocE/TOHkjcZeYd
                       i1ob2Kb6dQavWrUZWCTt5AAXzq6OVjePFJwuxWCLUme1A4ldBxyKMthm9LWMSyOr
                       YqTr+5q4I5XIBEMNrbS84PNAWsVlgQneEQBuoBcoXxjXzuIIHHJ9r/qhOlWb94mE
                       aiMcaLgJXQF3lPuu72di/osB0NEbzh3/TdNOY/Y/pDlQJlYVaYTZzPqoeifo57dO
                       MZ3I+FWwImerGG9Y4nh0VFDWgpa3Oza96gX/ljpOgTcDj8CYEzhJnRuZeQcgHcic
                       lgXxefVcspFFCT2ed55xMpH4XvXId13M6QKCAQAcDrrE96IuA2fkF6Hwb6cO8wiJ
                       Ro2aVQQ2dC6ag23cQrOywcAGfRId95MTtP3YeHL07tCSIX+3WjqqnzZsQFxBi6tQ
                       52gsirq53X8ZxDDUfjGMWreB1ZeqSrB2hYnB0ZctAnYBDkfKk1KG9INQWxUPWb/7
                       WEz1f59dECX7Z5A0lkTW3fon7kwj61Ccg7rcdOFaXkxv4sPgJU6b2jJd2mmw/H5A
                       JlPD8U2wOqnzAjScinL57GqUP4Pw08WxQCoknaFtc+5RJAVIoUTq/NSVNVX8wUIx
                       T9iDuU/0Oq9ADJefkgDFCu546hN1v5pxrZgffwax/C9yGB6UYDUssIE1Vg/k
                       -----END RSA PRIVATE KEY-----